lcm-proj/lcm

configure.ac
Removes jchart2d jar file from INSTALLED_CLASSPATH variable since it appears to be no longer installed.  It was getting propagated through to the pkg-config file which was causing MATLAB to throw an error when trying to add it to its path (Drake uses the .pc file to find the lcm.jar file).
Albert: can you confirm that the jchart2d jar is not installed anymore with your new build setup?
=> Removes jchart2d jar file from INSTALLED_CLASSPATH

lcm/lcm-cpp-impl.hpp, lcm/lcm-cpp.hpp
This is vital for performing special I/O tuning on the underlying FILE*
Sometimes calls such as fflush(), fileno(), setvbuf(), etc are required for performance reasons.
Without this call, the C++ API is unusable.
=> Added LogFile::getUnderlyingLogFile() for C++

lcm-java/lcm/logging/JScrubber.java
Ensures that once the user has clicked on a slider, the movement interaction remains on that slider, instead of jumping if the mouse moves over the other slider.  This removes the possibility of attempting to use the zoom slider carefully and accidentally jumping to a completely different part of the log.
=> Bugfix for dragging sliders in lcm-logplayer-gui

lcm-java/lcm/spy/ObjectPanel.java
Collapsing a multiple indented type would cause the indent level to go negative, making the types unreadable.  Thanks to Adam Bry for the help.
=> Fixes an issue with multiple indented types

lcmgen/emit_cpp.c
- Added cpp-std option
- Emitting ```static const``` for constants by default, and ```static constexpr``` for c++11. I think ```constexpr``` is more flexible that just ```const```, even though both works.
Let me know if there are any other C++11 issues that need to be resolved in this PR
=> add -cpp-std option

lcm-python/setup.py
`setup.py` in lcm-python should use `subprocess` to run `pkg-config`, instead of using the deprecated `commands` module
This allows installation of lcm in a python 3 `venv` using `pip`, e.g.:
```shell
(some-venv) $ pip install -e ~/Repositories/foss/lcm/lcm-python/
```
The change doesn't prevent the normal `./configure;make;make install` from working correctly with python 2.7 on my Mac. It also doesn't have a problem if you run `sudo python setup.py install` from within the lcm-python directory. 
However, it does seem to have an issue with using `pip` for python 2.7, where the explicit call to `sys.stdout.encoding` is returning `None` from within `pip` for 2.7, and `'UTF-8'` otherwise. This is not a problem with LCM, but may be a bug in `pip`. Removing `sys.stdout.encoding` solves the …
=> use subprocess module instead of deprecated commands module

lcm-java/lcm/spy/ObjectPanel.java, lcm-java/lcm/spy/Spy.java
- Fixes an issue where large graphs would stop updating when the ObjectPanel they came from was minimized (they still stop updating when the ObjectPanel is closed.)
- Fixes an issue where collapsed sections would cause sections below them to indent.
- Fixes an issue where the target for clicking on sparklines was slightly off
- Changes behavior for minimizing sections: reduces the click target from anywhere in the section that was not a sparkline to just the top bold text.  I think this is much more intuitive now, since there are other things to click, that are often clicked more than the section minimization.  This should reduce missed clicks causing sections to minimize.
Also cleans up trailing whitespaces and removes a few unneeded casts.
=> GUI improvements on ObjectPanel

lcm-java/lcm/spy/ObjectPanel.java, lcm-logger/lcm_logger.c, lcm/eventlog.c, lcm/ioutils.h, lcm/lcm_coretypes.h, lcm/lcm_file.c, lcmgen/emit_c.c, lcmgen/emit_cpp.c
This change fixes issues that were caused by the unspecified behavior when shifting a negative signed integer. This was being done in both the marshalling code, and message hash computation.
Most of the time, the compiler would treat them as unsigned, but in some rare circumstances (always with optimizations turned on) it would not give the expected result.
See Section 5.8 paragraph 3 of the standard
http://open-std.org/JTC1/SC22/WG21/docs/papers/2015/n4527.pdf
In the C/C++ lcm-gen, switch to using use uint64_t for computing the lcmtype hashes (the getHash() method still returns an int64_t since that is what goes across the wire).
In The marshalling code, cast to uint64_t before bit-shifting
There are a couple other minor changes that we had stored up in this branch as well.
=> Fix a dangerous bug in lcm's marshalling and hash functions.

lcm/Makefile.am
I know the official build process on windows is VS2013, but I've been building in cygwin from the stable release successfully. On git HEAD it fails linking liblcm.la, saying 
```
CCLD     liblcm.la
libtool:   error: can't build x86_64-pc-msys shared library unless -no-undefined is specified
Makefile:502: recipe for target 'liblcm.la' failed
```
The C bindings build correctly after adding `-no-undefined` to the libtool flags as done here.
There's still another issue with the java bindings I haven't worked out, where it fails with
```
/bin/sh: line 6: /c/Program: No such file or directory
```
This is because java (by default) is installed to "Program Files" which has a space in it. Going into the lcm-java/Makefile and adding quotes around the paths with for `JAR=` and `JAVAC=` solves it-- …
=> Fix build error under cygwin gcc.

lcm-java/Makefile.am
There seems to be a problem building lcm out of source. This change appears to fix the issues. I've tested the build in and out of source with this change on an Ubuntu system.
=> Fix lcm-java automake for out-of-source

lcm-java/Makefile.am
This avoids the error:
```
java.net.SocketException: Can't assign requested address
```
on OSX connected via WiFi (see [StackOverflow]).
I believe it shouldn't have any adverse effects for others, since I always see `lcm-spy` saying:
```
LCM: Disabling IPV6 support
```
anyway.
But if it causes problems for any users, just let me know and I'll look for a more general solution.
[StackOverflow]: http://stackoverflow.com/questions/18747134/
=> Add java option to prefer IPv4 in lcm-spy

lcm/dbg.h
VS2010 raises compiler warning
C4002: too many actual parameters for macro 'dbg'
if compiled with NO_DBG
=> Fix VS2010 compiler warning

WinSpecific/vs12/UseGlib.props, configure.ac, lcm-logger/lcm-logger.vcproj, lcm-lua/rock/LUAROCKS_INSTALL.md, lcm-lua/rock/lcm-1.3.0-0.rockspec, lcm-python/README, lcm-python/setup.py, lcm/lcm.pc.in, lcm/lcm.vcproj
Fixes #76. Updated dependency of glib-2.0 to require version 2.32 or
higher, where possible. I'm not sure if it's possible to express this
for the Windows build.
=> Remove old gthread-2.0 dependency

lcmgen/CMakeLists.txt
Remove clang address/memory sanitization options when building `lcmgen`, as it is known to be sloppy about memory management and (per the comment in the source) we don't really care, since non-systemic leaks in a short lived process like lcmgen aren't really a problem. However, building with sanitization results in a broken executable due to the errors.
Users might want to build with sanitization for the sake of the libraries, or because they are building LCM as part of a "superbuild" and have sanitization turned on for all subprojects. In particular, this is breaking drake: RobotLocomotion/drake#2708.
=> Disable sanitization in lcmgen

CMakeLists.txt, WinSpecific/README.txt, docs/content/build-instructions.md, docs/release_checklist, lcm-cmake/mkdist.cmake
Update build instructions to discuss the new CMake build system rather than autotools. Update release checklist. Create targets to automate creation of distribution tarballs (although, since with CMake we no longer need to package non-source-controlled files, these are just the tarballs created by `git archive`, and - since github also provides these - are mainly useful as a testing aid).
Caveat: I *think* the release instructions are correct, but haven't actually verified.
Also, @ashuang, if you've already done most of this sort of thing yourself, feel free to ignore this; if it's outdated/wrong/etc. I won't be offended :smile:.
=> Update documentation for CMake

CMakeLists.txt, cmake/FindPython.cmake, lcm-python/CMakeLists.txt
Create a simple `FindPython.cmake` module to find both the Python interpreter and libraries, using the install prefix of the former as a hint for the latter. This should reduce the chances of finding a mismatched interpreter and libraries, as can happen on some machines if an interpreter from a non-standard prefix is in the user's `PATH`. It also lets us simplify the logic to find "Python" by having one module that provides both components.
This specifically was causing problems on some OS X machines using Python from Homebrew.
=> Fix finding Python when multiple versions present

lcm-java/lcm-logplayer-gui.sh, lcm-java/lcm-spy.sh
The wrapper scripts use `!#/bin/sh`, not `#!/bin/bash`, and we'd prefer to avoid the latter in case of systems that don't have it, if possible. Accordingly, replace use of `${BASH_SOURCE[0]}` with plain old `$0`. These should be the same except if the script is sourced via another script, and it seems safe enough to assume that doesn't happen for these.
=> Avoid use of BASH_SOURCE in wrapper scripts

lcm-cmake/install.cmake, lcm/CMakeLists.txt
Introduce a new exported `INTERFACE` library, `lcm-coretypes`, which provides users a way to depend on the LCM headers without needing to link to the actual LCM library. LCM types libraries will likely want to "link" to this.
(In particular, C++ LCM types "libraries" are header-only with an include dependency on LCM but no link dependency. Consumers of these "libraries" need the LCM include directories, but may not need to link to the actual LCM library. The interface library gives consumers a way to make this work, conveniently.)
=> Create header-only link target lcm-coretypes

lcm-cmake/lcmUtilities.cmake, lcmgen/emit_lua.c, lcmgen/emit_python.c
Add support for generating Lua bindings using the CMake helpers. Add `--lua-no-init` option to `lcm-gen`, mirroring `--python-no-init`. Tweak wording of same. Fix a typo in the `lcmUtilities.cmake` documentation.
Note: Lua subpackages are not correctly supported at this time. (Patches from anyone needing this support are welcomed. The immediate goal is to get the unit tests working under CMake, which don't need this feature.)
=> Add Lua support to lcmUtilities.cmake

lcm-logger/lcm_logger.c, lcm/lcm.c
Fixes the Autotools build! (Oops.)
=> Remove references to deprecated g_thread_init

CMakeLists.txt, lcm-logger/CMakeLists.txt, lcm-pkgconfig/lcm.pc.in, lcm/CMakeLists.txt
Since df709cb616d7, we no longer need to link to gthread. Accordingly, remove it from our GLib required components and remove linking to it.
See also #94. @tprk77, assigning to you to verify that this is no longer needed, since it was your change that made this possible. I did also test it on Fedora and Windows.
=> Remove linking to gthread

test/cpp/CMakeLists.txt
- On CMake 3.1, 3.2 use add_dependencies instead of
target_link_libraries for lcm-test-types-generate-cpp.
@mwoehlke-kitware
=> tests/cpp fix for CMake < 3.3

lcm-java/lcm-spy.sh
I've encountered an issue with lcm-spy where lcm-spy spews many errors on startup, and refuses to open the structure viewer on any messages being seen (it spews similar errors when I try to open the structure viewer).
Errors look like this, though with varying classes within the jchart library:
```
ClassDiscoverer: java.lang.NoClassDefFoundError: info/monitorenter/gui/chart/IAxis
jar: /home/gizatt/lcm/build/lcm-java/lcm.jar
class: lcm/spy/ZoomableChartScrollWheel$5.class
``
Seems pretty clear that the cause is that the jchart library isn't being seen, even though it's in ```/usr/local/share/java``` right next to ```lcm.jar```. My naive, I-don't-know-any-java solution is attached. Is there a better way / some kind of system configuration I'm missing?
=> Explicitely add jchart to classpath on lcmspy launch

docs/content/tutorial-c.md, docs/content/tutorial-cmake.md, docs/content/tutorial.md, lcm-cmake/lcmUtilities.cmake
Add a "tutorial" for CMake, which presents a sample `CMakeLists.txt` for binding generation and explains it step by step. Add an additional helper function for installing headers. Change ref name of C tutorial to match others, for consistency.
@ashuang, I'd greatly appreciate any thoughts on wording or additional information you think would be helpful. (Also, since this is at least partly inspired by RobotLocomotion/drake#3426, I'll likewise invite @tkoolen to comment on the "adequacy" of this documentation.)
=> Add CMake tutorial, additional CMake helper functions

docs/CMakeLists.txt
Make .NET documentation depend on "main" documentation. Since both depend on erasing the old documentation directory first, and the .NET documentation lives in a subdirectory, this both ensures that the .NET documentation isn't the only documentation generated, and fixes an issue where the .NET documentation generation could fail if built first because the parent output directory doesn't exist.
@ashuang, since this is a trivial fix, I'll just go ahead and merge it if I haven't heard otherwise in a few days.
=> Fix dependency in documentation generation

lcm/CMakeLists.txt
Fixes typo introduced in #110 preventing ``sudo make install`` from succeeding:
```
CMake Error at lcm/cmake_install.cmake:40 (file):
file INSTALL cannot find "/home/wxm/software/lcm/build/lcm/lcm_exports.h".
Call Stack (most recent call first):
cmake_install.cmake:68 (include)
```
@mwoehlke-kitware could you please review and merge? The current tip of master is broken. Thanks
=> Fix typo: lcm_exports => lcm_export

lcm/ringbuffer.c
=> Avoid GCC warning about unused variable

docs/content/tutorial-cmake.md, lcm-cmake/config.cmake, lcm-cmake/lcmUtilities.cmake, lcm/CMakeLists.txt, lcmgen/emit_c.c, test/types/CMakeLists.txt
Teach `lcmgen` to add export decorations to the generated C bindings, and to include a header defining the export symbol. Modify CMake `lcm_wrap_types` helper to leverage this. Update test types to use it (bringing us closer to being able to build shared on Windows; #112 still needs to be addressed). Update CMake tutorial to cover this.
Fixes #111.
=> Teach lcmgen to export decorate bindings

CMakeLists.txt, lcm-cmake/config.cmake
Set [`CMP0063`](https://cmake.org/cmake/help/v3.3/policy/CMP0063.html) to `NEW`, silencing configure warnings about said policy. Also set visibility preset for C, so that LCM bindings and the core LCM library are actually affected. (Previously, only gtest was honoring visibility, since that is the only C++ library.) Note that this required the recently merged changes (#116) to add ABI decoration to bindings.
=> Fix issues related to CMAKE visibility options

lcm-python/.gitignore, test/python/.gitignore
Modify `.gitignore` in lcm-python to enforce that the ignored `build` directory a) is actually a directory, and b) is exactly where we expect it. This will continue to ignore what we intend to ignore, but won't ignore some things that would match the old rule but aren't what we intend to ignore. Add an ignore for the `.pyc` generated from the test `client.py` when running the unit tests.
=> Tweaks to .gitignore

lcm-python/setup.py
Add the top level source directory to the includes when building the Python module with `setup.py`. This is needed for some source files to find their includes. (I'm not sure if this is a regression that got overlooked at some point, or if it just never worked...)
=> Fix include directories for setup.py

docs/content/build-instructions.md
Add a note to the build instructions recommending users to refer to the in-source version of the document if building an old or bleeding edge version of LCM.
This doesn't precisely fix #117, but should mitigate such issues going forward.
=> Mention that build doc may be crufty

lcm-cmake/lcmUtilities.cmake, lcm-python/CMakeLists.txt, lcm-python/module.c
Use `distutils` to query the location where Python modules should be installed. This fixes installation on Debian and derivatives which use the non-standard `dist-packages` instead of `site-packages`. (It's also more robust, since obviously asking Python is always going to be better than trying to replicate its logic.) Also, add missing ELF export decoration for the Python module entry.
Fixes #127.
=> Fix Python install location, export entry point

lcm-lua/init.c
Add missing export decoration for Lua module entry point. This fixes the Lua module that stopped working when ELF hidden visibility was enabled. (I'm not sure about Windows, as I don't have Lua on Windows, but I suspect it never worked on Windows.)
=> Fix export decoration of Lua module

lcm-java/CMakeLists.txt
Add an option to specify the Java version for which to build the Java components. By default, this is set to 1.6. This should help e.g. MATLAB users that need to use LCM from within an older JVM than the system's default JVM. (Note that autotools did something similar.)
This is a minor improvement (adding the option) over #137. @wxmerkt, if you can confirm this approach works for you, I'll go ahead and merge it, seeing as @ashuang already approved the idea (unless I hear objections, of course).
=> Target Java 1.6 by default

lcm-cmake/install.cmake, lcm/CMakeLists.txt
Rename static library from `lcm-static.a` to `lcm.a` (except on Windows, where this would collide with the import `.lib` for the shared library). Use `export(EXPORT` instead of `export(TARGETS` to create the build-directory target exports file, which avoids having to maintain a One True List of exported targets (which was missing `lcm-static`).
Besides seeming like more logical naming, this should allow pkg-config users to choose between static and shared libraries by wrapping LCM's link arguments with `-Bstatic`/`-Bdynamic`.
=> Minor fixes to static library and install rules

lcm-java/CMakeLists.txt, lcm-java/jchart2d-code/CMakeLists.txt, lcm-java/lcm-logplayer-gui.sh, lcm-java/lcm-spy.sh.in
Modify lcm-spy and jchart2d build to allow use of system versions of xmlgraphics-commons and jide-oss. This is important for packaging, since distros are likely to not appreciate us installing our own versions, when these are provided by the distro.
=> Add ability to use system third-party JAR's

lcm/lcm_version.h
Bump the version number, so that users can tell the difference between v1.3.x (LTS) and what will eventually be 1.4.x. Since we can't readily add trailer tags, and since they make version comparisons a pain, this uses the convention of using a very large number for the patch version.
=> Bump version to 1.4.0 pre-release (1.3.95)

lcmgen/CMakeLists.txt
Remove everything that looks like a sanitizer flag when building lcm-gen. This will catch other sanitizers, as well as supplemental sanitizer related flags besides `-fsanitize=<type>`, which also need to be stripped to prevent the compiler complaining about them when the  'main' flag has been stripped.
See also 6eb8668f3323 and the comment added to the CMakeLists.txt for rationale.
=> Aggressively disable sanitization in lcmgen

lcmgen/CMakeLists.txt
Add a warning when sanitizers are being disabled for `lcmgen`, and an option (hidden unless applicable, and advanced when applicable) to override this behavior.
=> Make lcmgen no-sanitize optional

lcmgen/emit_c.c, lcmgen/emit_cpp.c
Make the include guards in the C and C++ headers generated by `lcm-gen` span all of the file, including the `#include` list, by moving up the appropriate `#ifndef`/`#define` statements generated.
Having all of the header inside the include guards makes it manifest that the header can be `#include`-ed twice in client code without any side effects. This helps both the reader of the file, and static analysis tools that may warn about including a generated header twice unless we make it obvious that there is an include guard protecting the entire header file.
=> Make lcm-gen C/C++ include guard span includes

lcm/lcm_coretypes.h, lcmgen/emit_c.c, lcmgen/emit_cpp.c
ISO C++ forbids casting between pointer-to-function and pointer-to-object. Storing a pointer-to-function (pointer to getHash()) in a `void *` is not allowed, and will result in a compiler error when using pedantic compiler flags.
This patch resolves the issue by storing the pointer-to-function in a field of the correct pointer-to-function type.
=> Correct pointer-to-function type in lcm-gen C/C++

lcm-logger/lcm_logger.c
Make the write thread of `lcm-logger` write out all messages remaining in the queue before exiting. This means that messages received by `lcm-logger` before the `lcm-logger` was asked to terminate end up in the log.
This fixes lcm-proj/lcm#173.
=> Make lcm-logger flush queue before exiting

lcmgen/emit_cpp.c
When building C++ code generated by `lcm-gen` using Clang, a warning about implicit conversion that changes signedness is triggered (`-Wsign-conversion`). This patch fixes the warning by making the conversion explicit, using `static_cast<int64_t>()`.
=> Fix Clang -Wsign-conversion warning in lcm-gen C++

lcmgen/emit_cpp.c
Here's a possible fix for #164.
If anyone is using LCM in an environment with exceptions disabled, then this fix wouldn't be appropriate.
=> C++ bindings: catch exception from bad vector resize

lcm-java/lcm/logging/Log.java
Remove unused imports `java.awt.*`, `java.awt.event.*` and `java.util.*` from `lcm-java/lcm/logging/Log.java`. It is worth noting that importing `java.awt.*` doesn't work on Android; removing these unused imports makes it possible to use LCM in Android apps.
=> Remove unused imports in lcm/logging/Log.java

lcm-cmake/install.cmake
so other projects can use this one without requiring
to install the package. See cmake [documentation](https://cmake.org/cmake/help/v3.7/command/export.html?highlight=export) section "export(PACKAGE <name>)" for further info in this.
=> cmake: export cmake build to CMake's user registry

lcm/lcm_file.c, lcm/lcm_memq.c, lcm/lcm_mpudpm.c, lcm/lcm_tcpq.c, lcm/lcm_udpm.c
There seem to be at least two data races on lcm.vtable in lcm.c and udpm.c.  To reproduce the bug, I just modified the listener.cpp in the example folder:
https://gist.github.com/m-chaturvedi/4bce669434d2d197170b1ead1be97438 
If tsan is used on the above in addition to LCM, we can see that there are data-races.
Seems like we don't need to free the mutexes on static objects:
https://developer.gnome.org/glib/stable/glib-Deprecated-Thread-APIs.html#g-static-rec-mutex-free
=> Fixing a ThreadSanitizer Issue

CMakeLists.txt, lcm-cmake/cpack.cmake
Add CPack support. Default generators are TGZ and STGZ. DEB generator is added if building under Debian, Ubuntu or LinuxMint.
=> cmake: add CPack support

lcm/eventlog.c
Towards https://github.com/lcm-proj/lcm/issues/194
Should `magic` be of unsigned type? 
And probably we could rely on `MAGIC`'s promotion to unsigned when comparing `MAGIC` with `magic`.
=> Fixing a UBSan Bug in eventlog.c

lcmgen/emit_cpp.c
Using a C-style cast in C++ code triggers `-Wold-style-cast` in both GCC and Clang, and because lcm-cpp is header-only it is sometimes difficult for downstream projects to suppress this warning in LCM-generated code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lcm-proj/lcm/199)
=> In generated C++ code, use static_cast instead of C cast

lcm-python/CMakeLists.txt
Patch taken from [here](https://s3.amazonaws.com/drake-homebrew/patches/lcm-1.3.95-python-undefined-dynamic-lookup.patch).
http://blog.tim-smith.us/2015/09/python-extension-modules-os-x/
To test:
`diff <(otool -L $INSTALL1/lib/python2.7/site-packages/lcm/_lcm.so) <(otool -L $INSTALL2/lib/python2.7/site-packages/lcm/_lcm.so)`
=> Use -undefined dynamic_lookup for OSX

lcm-cmake/cpack.cmake
`lsb-release` is not available on all distribution, but `/etc/lsb-release` file
is normally available, so `lsb-release` executable call is replaced by reading
`/etc/lsb-release` text file instead. Platform is named "amd64" instead of
'x86_64' to match Debian and Ubuntu package names.
=> Improve packaging for Linux

lcm-java/lcm/spy/ObjectPanel.java
In the `lcm-spy` structure viewer, if `unindent()` is called after `collapse_depth` is decremented, arrays of  LCM types do not render correctly when some of the array elements are collapsed.
Rendering with the current master branch:
Rendering after this change:
=> Prevent unindenting in the middle of an array in lcm-spy

lcmgen/emit_c.c, lcmgen/emit_cpp.c, lcmgen/main.c
Add an option to use double quotes instead of angular brackets when including headers in the header files generated by `lcm-gen`.
The convention seems to be to use angular brackets for system includes.
The main difference is that the current directory is searched first and then include directory list when using double quotes, whereas the current directory is not searched when using angular brackets.
=> Add option to include with quotes instead of angular brackets

lcmgen/main.c
This change adds result code propagation to exit code whenever a
code generation error happens. If any code generator fails main
exits with -1.
=> Propagate exit code from generation errors to main

lcm/lcm_coretypes.h
@fbudin69500 filed a [bug at LLVM](https://bugs.llvm.org/show_bug.cgi?id=37350) which demonstrates this problem with clang.
Sorry to have not found in the previous PR.  
I don't think the [`pragma` is defined in MSVC](https://msdn.microsoft.com/en-us/library/d9x1s805.aspx), thus the `#if`.
=> Circumvent LLVM problem with old style casts

.clang-format, format_code.sh
First commit adds a script to use `clang-format` to format code.
Second commit actually formats code.
=> Code formatting

AUTHORS, CMakeLists.txt, README.md, cmake/FindGo.cmake, docs/content/mainpage.md, docs/content/tutorial-go.md, docs/content/tutorial-lcmgen.md, docs/content/tutorial.md, examples/.gitignore, examples/go/gen.go, examples/go/listener/main.go, examples/go/sender/main.go, lcm-cmake/lcmUtilities.cmake, lcm-go/README.md, lcm-go/lcm/lcm.go, lcm-go/lcm/lcm_test.go, lcmgen/CMakeLists.txt, lcmgen/emit_go.c, lcmgen/lcmgen.c, lcmgen/lcmgen.h, lcmgen/main.c, test/CMakeLists.txt, test/README, test/go/CMakeLists.txt, test/go/client_test.go, test/types/CMakeLists.txt
Hi, this patch set contains backend support and code generation output for the Go language [golang](https://golang.org/) through the `-g` option.
The golang code generation implements the golang BinaryMarshaller interface in order to be as idiomatic as possible.
The patch set incorporates and is dependent on the changes that are part of the pull requests #217, #218, #219. Thus they should be merged before this pull request is considered.
Co-authored with @TacoVox
=> Add golang backend support and code generation

examples/c/listener-async.c, examples/c/listener-glib.c, examples/c/listener.c, examples/c/read_log.c, examples/c/send_message.c, examples/cpp/listener.cpp, examples/cpp/read_log.cpp, examples/cpp/send_message.cpp, format_code.sh, test/c/client.cpp, test/c/common.c, test/c/common.h, test/c/eventlog_test.cpp, test/c/memq_test.cpp, test/c/server.c, test/c/udpm_test.cpp, test/cpp/client.cpp, test/cpp/common.cpp, test/cpp/common.hpp, test/cpp/memq_test.cpp
Formatting for `examples` and `test` directories. I also needed to update the formatting script to exclude things like the `gtest` directory.
=> Formatting of examples and test

lcm/lcm_udpm.c
Binding to INADDR_ANY causes us to receive datagrams destined for our
port to any address, which can be problematic if, for example, there
are different LCM publishers using different multicast addresses and
the same port.
=> Bind the UDP receive port to the desired address.

lcmgen/emit_go.c
For this definition:
```
package GoGen;
struct Bug
{
PkgA.A  a;
PkgA.B  b;
}
```
The Go code generator generates two import statements for PkgA:
```
// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen
package GoGen
import (
"encoding/binary"
"fmt"
"math"
"math/bits"
"PkgA"
"PkgA"
)
...
```
This results in Go compile error:
```
src/GoGen/Bug.go:14:2: PkgA redeclared as imported package name
previous declaration at src/GoGen/Bug.go:13:2
```
This Dockerfile can be used to reproduce the issue:
```
FROM golang:1.10
RUN apt-get update && apt-get install -y \
build-essential \
libglib2.0-dev \
cmake \
python-dev \
python-epydoc \
openjdk-8-jdk \
lua5.2-dev \
doxygen
RUN git clone --branch v1.4.0 --depth 1 https://github.com/lcm-proj/lcm.git && \ …
```
=> Don't import the same package multiple times in generated Go code.

lcm-go/lcm/lcm.go
Due to the modification of the passed LCM instance both the call to
UnsubscribeAll() and the deletion of the instance from the global list
of subscriptions failed. Additionally, the flag indicating a closed
channel was not set for the actual LCM instance.
This fixes lcm-proj#270.
=> Fixed destructor logic for LCM instance.

lcm-go/lcm/lcm.go, lcm-go/lcm/lcm_test.go
The Go bindings did not allow the selection of the underlying LCM
provider. This change adds the possibility to select the desired
provider by passing the corresponding string to NewProvider().
=> Added selection of LCM provider to Go bindings.

lcm/lcm-cpp-impl.hpp
This avoids a race condition where a receiving thread could
potentially try to handle an incoming message (as far as the C
implementation is concerned, we're done subscribing) before the
handler is populated (and then trying to run a handler at address
0x0).
=> Always initialize context and handler before calling lcm_subscribe

lcm-java/lcm-logplayer-gui.sh
Remove the `-Xincgc` option from `lcm-logplayer-gui.sh`, since it is no longer supported (see [this](https://stackoverflow.com/questions/54854750/eclipse-unrecognized-option-xincgc)).
The JVM is correctly created now, and the GUI runs normally.
=> Remove deprecated garbage collection flag for `lcm-logplayer-gui`.

lcm-cmake/lcmUtilities.cmake
if there is no package prefix, the old behavior would result in an underscore
'_' being erroneously prefixed to generated source code filenames. new behavior
will only concatenate the package prefix if the LCM message definition file in
question has specified a package.
=> add package prefix check when generating C libraries in CMake

lcm-cmake/lcmUtilities.cmake
The fix in 27902c3 won't work when applied on top of f485e38414e71987d40cea17f289f0cc1759576e. This fix solves the problem 27902c3 was meant to solve.
Thanks
=> Use STREQUAL instead of DEFINED to check if package is set in lcm file

lcm-cmake/lcmUtilities.cmake
Adding the option to generate C# wrappers in `lcmUtilities.cmake`.
Thanks
=> Add possibility to generate C# wrappers

lcm/lcm_mpudpm.c, lcm/lcm_udpm.c
Binding to INADDR_ANY causes us to receive datagrams destined for our port to any address, which can be problematic if, for example, there are different LCM publishers using different multicast addresses and the same port.
This reverts commit 6b9099a15675794a94d7198dd69840bcd5432f25, reapplying 76066294b6d008cb6b81e7027382e1104395277c but with a WIN32 guard now to retain the INADDR_ANY behavior on windows, as well as newly applying the same fix to mpudpm.
Closes #301.
=> Bind the UDP receive port to the desired address

lcm/lcm-cpp-impl.hpp, lcm/lcm-cpp.hpp
Simply adds a member to Subscription for storing the string and passes the string back to the callback handler.
Fixes #313
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lcm-proj/lcm/314)
=> Removed implicit string conversion from const char* to std::string during subscription handling

lcmgen/emit_csharp.c
Use `sbyte` (signed byte) instead of `byte` when generating C# code for `int8_t` type.
Closes #318.
=> lcmgen use sbyte for int8_t when generating C# code

docs/Doxyfile.in
The [official docs for the `LCM` class (C++)](https://lcm-proj.github.io/classlcm_1_1LCM.html) omit the [c++11 overload of `.subscribe()`](https://github.com/lcm-proj/lcm/blob/master/lcm/lcm-cpp.hpp#L426).
This PR asks that the `LCM_CXX_11_ENABLED` preprocessor directive be set in the doxyfile so that this overload appears in the generated API documentation.
=> Add LCM_CXX_11_ENABLED to doxygen compiler flags.

lcmgen/emit_python.c
`_hash` appears to be vestigial. `_packed_fingerprint` is the member that actually caches the computed lcm hash for the type.
Also, `_hash` is very close to python's magic `__hash__` method, so this is a confusing artifact that should be removed.
=> Remove unused `_hash` member from python lcmtypes

lcmgen/emit_python.c
In response to #339 
I considered making it a function, `get_hash()`, a member variable, `hash`, or a property, `hash`. In the end I settled for a property since it is more elegant than the function and, in contrast to a member variable, it's read-only.
=> Add `get_hash()` to generated python classes

lcm/lcm_mpudpm.c, lcm/lcm_udpm.c, lcm/udpm_util.c, lcm/udpm_util.h
In using LCM I noticed message loss of packets greater than a UDP datagram occasionally. I was able to track it down due to receiving out of order fragments likely due to UDP. I pulled PR #175 into my local repository after noticing it was previously discovered, and after some extensive testing confirmed this resolved my issues. Opening this PR as there were some merge conflicts that needed resolution, and I did not have access to the original branch to resolve them.
Overview of changes, copied from this PR:
lcm_frag_buff type has an extra pointer and an extra uin32_t conatined within a new struct
More packets could potentially wind up in the fragment hash table
Hashing function has an additional multiplication
Hash pointer equality check has an additional condition
=> Fix issues with out of order udp packets in udpm and mpdupm dropping messages.

lcmgen/emit_java.c
=> lcmgen: Avoid java errors on byte arrays with int64_t lengths

lcm/lcm_mpudpm.c
When parsing UDP packets that are not valid LCM messages, the
mpudpm module's error handling would get the internal locks into
an invalid state. When attempting to read the next UDP packet, it
would abort() with the following message on some platforms:
Attempt to unlock mutex that was not locked
Fix this by re-acquiring the receive lock during error handling
so the next unlock at the top of the recv loop will not crash.
Signed-off-by: Brian Kubisiak <brian@kubisiak.com>
=> mpudpm: fix lock sequence while parsing packets

lcm-python/module.c
While trying to migrate Homebrew formula to Python 3.11, I hit the following error:
```
/tmp/lcm-20221118-59422-1wlr2mm/lcm-1.4.0/lcm-python/module.c:46:34: error: expression is not assignable
Py_TYPE(&pylcmeventlog_type) = &PyType_Type;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/tmp/lcm-20221118-59422-1wlr2mm/lcm-1.4.0/lcm-python/module.c:47:26: error: expression is not assignable
Py_TYPE(&pylcm_type) = &PyType_Type;
~~~~~~~~~~~~~~~~~~~~ ^
/tmp/lcm-20221118-59422-1wlr2mm/lcm-1.4.0/lcm-python/module.c:48:39: error: expression is not assignable
Py_TYPE(&pylcm_subscription_type) = &PyType_Type;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
3 errors generated.
make[2]: *** [lcm-python/CMakeFiles/lcm-python.dir/module.c.o] Error 1
```
Added a fix used by other projects like:
- `boost` - …
=> Fix compatibility with Python 3.11

lcm-logger/glib_util.c, lcm-logger/lcm_logger.c, lcm/lcm.c, lcm/lcm_file.c, lcm/lcm_internal.h, lcm/lcm_memq.c, lcm/lcm_mpudpm.c, lcm/lcm_tcpq.c, lcm/lcm_udpm.c, lcm/udpm_util.h, liblcm-test/lcm-tester.c
I tried to achieve some basic organization with each commit.  The first hits the Thread API, then GTimeVal, and the third GStaticPrivate.  The last commit is just updating the GLib version check to `2.32.0`.
Mainly, this is just find and replace stuff.  The only tricky part was taking an `int64_t` returned from `g_get_real_time()` and splitting it out into a `struct timeval` for the `select` function's timeout parameter.  You can see that in `lcm/lcm_udpm.c`.
I ran the tests with `make test` in fc37, ubuntu 22.04, and ubuntu 20.04 containers and all tests passed.  Also ran some log file playback and everything seemed unchanged.
Closes #65.
=> Fix GLib bitrot

lcm-python/pylcm.c
`PyEval_CallObject` was deprecated in [`3.9`](https://docs.python.org/3/whatsnew/3.9.html#changes-in-the-c-api) and `PyObject_CallObject` has been available since at least [`2.7`](https://docs.python.org/2.7/c-api/object.html?highlight=pyobject_callobject#c.PyObject_CallObject) and [`3.5`](https://docs.python.org/3.5/c-api/object.html?highlight=pyobject_callobject#c.PyObject_CallObject).
=> lcm-python: replace PyEval_CallObject with PyObject_CallObject

.github/workflows/test.yml
GH-381 introduced a bug where some junk was copy-pasted from the docs deploy job into the docs test job, causing all non-master pushes and PRs to fail. This PR removes that junk.
=> remove environment specification from docs test

lcm/lcm_mpudpm.c, lcm/lcm_udpm.c, lcmgen/emit_go.c
Fixes the following warnings on `master`:
```
lcm/lcm_mpudpm.c:401:14: warning: assignment to ‘struct sockaddr_in *’ from incompatible pointer type ‘struct sockaddr *’ [-Wincompatible-pointer-types]
401 |     key.from = &(lcmb->from);
lcm/lcm_udpm.c:246:14: warning: assignment to ‘struct sockaddr_in *’ from incompatible pointer type ‘struct sockaddr *’ [-Wincompatible-pointer-types]
246 |     key.from = &(lcmb->from);
lcm/lcmgen/emit_go.c:1150:9: warning: unused variable ‘readVar’ [-Wunused-variable]
1150 |     int readVar = 0;
lcm/lcmgen/emit_go.c:102:14: warning: ‘first_to_upper’ defined but not used [-Wunused-function]
102 | static char *first_to_upper(const char *const str)
lcm/lcmgen/emit_go.c:51:14: warning: ‘dots_to_underscores’ defined but not used [-Wunused-function]
51 | static …
```
=> Clean up a few C compiler warnings

README.md, docs/release_checklist, lcm-lua/rock/lcm-1.4.0-0.rockspec, lcm/lcm_mpudpm.c, lcm/lcm_udpm.c, lcm/udpm_util.c, lcmgen/emit_go.c
This PR:
- Updates links to point at the automatically-updating pages (http://lcm-proj.github.io/lcm) rather than the manually-updated pages (http://lcm-proj.github.io)
- Removes manually updating the docs from the release checklist, since this is now automated
=> Docs: update links to pages

lcm-java/lcm/lcm/LCM.java, lcm-java/lcm/spy/Spy.java
I use LCM with multiple multicast addresses at the same time. It'd be useful for my team if there were option to have more detailed window titles than just "LCM Spy" when using multiple windows. 
```
-t, --title [LABEL]    Display LABEL in the window title
--title-url            Display the LCM URL in the title
```
Example usages:
```
./lcm-java/lcm-spy --title 'Alice' --title-url
./lcm-java/lcm-spy -l 'udpm://239.255.76.67:8888' --title-url
./lcm-java/lcm-spy -t Bob
```
Added public static `LCM.getDefaultURL`.
I made and used `WindowTitleOptions` as I would in C. I find this *clean* enough, but if desired I can add java style boilerplate and maybe follow a builder pattern or something. 
After feedback, I'd like to add these options [and maybe  also `--title-filename`] to …
=> Lcm-spy: Add cli params for the window title

test/c/CMakeLists.txt, test/c/common.c, test/c/common.h, test/c/eventlog_test.cpp
This addresses the linker warning:
```
CMakeFiles/test-c-client.dir/common.c.o:common.c:function make_tmpnam: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
```
I'm assuming that `g_mkstemp` is a suitable replacement on the Windows platform but I'm not currently setup to test.  Since this only impacts the eventlog tests, I thought this was a low risk change.
=> Replace tmpnam with mkstemp

.github/workflows/test.yml, test/lua/CMakeLists.txt
This PR:
- splits up build job into ubuntu and mac
- adds lua dependency for each job
- disables failing lua test (#393)
=> Enable Lua on CI

cmake/FindGLib2.cmake
It appears that all that is needed here is to pass `NAME_MISMATCHED` to avoid the following warning when running `cmake`.  Took this path since the [docs](https://cmake.org/cmake/help/latest/module/FindPackageHandleStandardArgs.html#command:find_package_handle_standard_args) indicate this is the intended way to handle mismatched names for packages.  They do note that this is usually a mistake but since LCM has been working this way for quite a while I tend to think this is an exception.
```
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
The package name passed to `find_package_handle_standard_args` (GLib2_glib)
does not match the name of the calling package (GLib2).  This can lead to
problems in calling code that expects `find_package` …
```
=> Pass NAME_MISMATCHED to avoid warning

lcm-java/lcm/logging/LogPlayer.java
Can now say --lcm-url=udpm://239.255.76.67:8888?ttl=1 Before `=1` was stripped out.
Correctly error out (show usage instead of crashing) when argument params are not provided.
[whitespace: Used vscode `Format  Selection` on parsing block]
=> logplayer-gui: Fix cli parsing errors

lcm-java/lcm/logging/LogPlayer.java
as PlayerThread gets to sleep  for waitms time then you would hit stop/pause after you already called log.readNext so you will always skip what you read once you play again 
so the fix purposes to log the each time we run playthread so in case we get interrupted during sleep of waitms then we can get back to where the last play was trying to play but its time didn't come yet
=> fix play-pause play issue  #327

.github/workflows/test.yml, lcm-logger/lcm_logger.c, lcm-lua/lualcm_hash.c, lcm-lua/lualcm_pack.c, lcm-lua/utf8_check.c, lcmgen/emit_go.c, lcmgen/emit_lua.c, lcmgen/emit_python.c, test/cpp/common.cpp
This PR:
- Adds `-Werror` as a compiler argument for both C and C++
- Fixes warnings so it compiles warning-free on the Ubuntu and macOS CI targets
Warnings fixed:
- `format-overflow`:  9c7a4a47d14dbce11e9fea01217c969c2539b9ea
- `GLib-CRITICAL **: 10:09:34.795: g_hash_table_destroy: assertion 'hash_table != NULL' failed` warnings while running lcm-gen: af37954152982da00ef1892cfd75ce97a7b56ccb
- `Wshift-op-parentheses`: 1927a43dc167425bedfb2345c7897c5eb7e3e134
- `Wswitch`: a4d7fac403c2cff17a07f1dabc2950b4e367a22c
- `Wpointer-sign`: e520e621feb3158721d079ae64ffb959d2e2325b
- `Wtautological-constant-out-of-range-compare`: 52073cf738f34a95e57e4592e302f23993d79234
- `Wdeprecated-declarations`: 405c5c6500162be10a5b6056bcf0aab45149e7d5
- `Wformat`:  42a5b611cd5d59ced9c76e935328da7ea4597915
I …
=> Fix compiler warnings and turn on werror on CI

lcm-java/lcm/logging/LogPlayer.java
Matching the new args added to lcm-spy by #389 :
```
-t, --title [LABEL]    Display LABEL in the window title.
Defaults to the log filename.
--title-url            Display the LCM URL in the window title.
```
The log filename is now displayed in the title if a different title isn't given.
If the file chooser gui is canceled, the app now closes. [I don't see a reason to remain running if there is no other way to select a log].
Example usages:
```
./lcm-java/lcm-logplayer-gui # Will exit if you hit cancel
./lcm-java/lcm-logplayer-gui loggylog.log 
./lcm-java/lcm-logplayer-gui loggylog.log --title "Alice"
./lcm-java/lcm-logplayer-gui loggylog.log -l 'udpm://239.255.76.67:8888?ttl=1' --title-url
```
=> logplayer-gui: Window title options

.github/workflows/test.yml, examples/c/CMakeLists.txt, examples/cpp/CMakeLists.txt
@ihilt pointed out that one significant downside of the current approach is that it tests building the examples using the latest package's version rather than the current revision, which may lead to headache down the road. 
This PR:
- fixes the above issue by moving the examples test into the `ubuntu` and `macos` jobs. 
- tests installing LCM from cmake on the CI 
- builds the examples on the macos target
-  some small modifications to the `CMakeLists.txt`s was necessary to support this
=> Refactor Examples CI Tests

docs/CMakeLists.txt, lcm-python/CMakeLists.txt, test/python/CMakeLists.txt
This PR fixes the following warnings, which occur while configuring a build directory:
```
<string>:2: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
<string>:2: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
```
These happen because of a this code block which occurs in three places in the current revision:
```
execute_process(
COMMAND "${PYTHON_EXECUTABLE}" -c "if True:
from distutils import sysconfig as sc
print(sc.get_python_lib(prefix='', plat_specific=True))"
OUTPUT_VARIABLE PYTHON_SITE
OUTPUT_STRIP_TRAILING_WHITESPACE)
```
On my system, `PYTHON_SITE` ends up being `lib/python3/dist-packages`. This variable is used to set the output of …
=> Update Python paths

test/java/lcmtest/LcmTestClient.java
Resolves the unchecked call warning below.  Unsure whether adding the `type.class` parameters is necessary but I didn't know of another way to do this.
```
lcmtest/LcmTestClient.java:138: warning: [unchecked] unchecked call to getConstructor(Class<?>...) as a member of the raw type Class
msg = (MsgType)type_.getConstructor(DataInput.class).newInstance(ins);
^
where T is a type-variable:
T extends Object declared in class Class
lcmtest/LcmTestClient.java:138: warning: [unchecked] unchecked cast
msg = (MsgType)type_.getConstructor(DataInput.class).newInstance(ins);
^
required: MsgType
found:    Object
where MsgType is a type-variable:
MsgType extends LCMEncodable declared in class LcmTestClient.MessageTester
2 warnings
```
=> Use generic type symbol for type_ in MessageTester class

CMakeLists.txt
Fixes the warning:
```
CMake Warning (dev):
-- Generating done
Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
--help-policy CMP0042" for policy details.  Use the cmake_policy command to
set the policy and suppress this warning.
MACOSX_RPATH is not specified for the following targets:
lcm-test-types-c
This warning is for project developers.  Use -Wno-dev to suppress it.
```
=> Set CMAKE_MACOSX_RPATH on macOS to satisfy policy CMP0042

lcm-python/CMakeLists.txt
This resolves the warning `ld: warning: -undefined dynamic_lookup may not work with chained fixups`.
The `-undefined dynamic_lookup` flag is used for linking with Python.  The best summary I could find is from the [CPython project](https://github.com/python/cpython/issues/97524#issuecomment-1458855301).  So, for our currently targeted MacOS version (14.2), `-Wl,-no_fixup_chains` is valid and silences this warning.  Compared to using chained fix-ups, the only potential downside for us is a slightly larger dylib, AFAICT.
=> Add -Wl,-no_fixup_chains for macos build

.github/workflows/test.yml
This PR ramps up automated testing in preparation for the next release. It makes the following changes:
- Switches from `foo-latest` labels to version-specific labels.
- Adds additional tests on `ubuntu-20.04`, `macos-11`, and `windows-2019` runners
- Switches the lua version on the Ubuntu target to 5.3, since both versions of Ubuntu have that package. If it's important to test on 5.4 then I can just split up the Ubuntu job into two jobs.
=> More CI targets

docs/content/build-instructions.md
I was unsure whether to leave `default-jdk` in there since we're testing against a specific version.  Removed golang since it's not built anyway.  Specified `lua` `5.3` since that's what we're testing against.
=> Update packages needed for building

docs/CMakeLists.txt, docs/content/build-instructions.md, docs/content/tutorial-dotnet.md, docs/doxygen_output/c_cpp/html/group__LcmC.rst, docs/doxygen_output/c_cpp/html/group__LcmCpp.rst, docs/doxygen_output/lcm-dotnet/html/namespaces.rst, docs/index.rst, docs/javadocs/index.rst, docs/redirect.html, lcm-java/CMakeLists.txt
This PR:
- Updates the shell commands in the build instructions so they aren't prefaced by the `$` (makes it more copy/paste-able for shells like `zsh`
- Adds the C, C++, C#/.NET, and Java APIs to the toctree
- Hacks the doxygen main pages to redirect to the main docs 
- Resolves #419
=> Miscellaneous Documentation Fixes

docs/CMakeLists.txt
Allow `lcm-java/CMakeLists.txt` to have control over adding `doc-java` to the `doc` target since it is created there.
This resolves the following error:
```
CMake Error at docs/CMakeLists.txt:59 (add_dependencies):
The dependency target "doc-java" of target "doc" does not exist.
```
Observed on Fedora 37.
=> Remove doc-java from top-level docs CMakeLists.txt

lcm-python/CMakeLists.txt
74a323fe8b071171ca4750bb95e34a6b4340bcbf changed `PYTHON_SITE` from a relative path to an absolute path which breaks custom install locations specified via ` -DCMAKE_INSTALL_PREFIX` when configuring a build directory (`DESTDIR` and `--prefix` still seem OK). This happens because `install` ignores `CMAKE_INSTALL_PREFIX` if the given install location is an absolute path.
This PR makes it so that `PYTHON_SITE` should be the same as it was before 74a323fe8b071171ca4750bb95e34a6b4340bcbf. In addition to testing locally, I [tested on our CI targets](https://github.com/nosracd/lcm/actions/runs/4491242361) with a series of test commits which refactored the CI to set `CMAKE_INSTALL_PREFIX`.
=> Fix Custom Install Location

.github/workflows/test.yml
This PR is partially motivated by #429 and partially just intended to make test failures more clear in general. It was tested [here](https://github.com/nosracd/lcm/actions/runs/4491683768).
=> Run ctest with --output-on-failure

lcm-python/pyeventlog.c
The [`Py_BuildValue` format string specification](https://docs.python.org/3/c-api/arg.html#strings-and-buffers) being used in `pyeventlog.c`, `"y#"` expands to a `char *` and a `Py_ssize_t` parameter. The values passed in at the corresponding va_arg positions are `char*` and `int32_t`, respectively.
On Intel Macs, `int32_t` is not aligned to the same 64-bit boundary as `Py_ssize_t`, making this an invalid cast.
The symptom is a `MemoryError` which occurs when trying to `read_next_event()`
```
python3 -c 'import lcm; lcm.EventLog("path-to-an-event.log").read_next_event()'
```
The problem has been demonstrated by @ihilt with a [CI pipeline](https://github.com/ihilt/lcm/actions/runs/4577228192/jobs/8082384702#step:6:31) based on [this …
=> Mac MemoryError caused by interpreting _lcm_eventlog_event_t's datalen and channellen as 64 bit

README.md, docs/release_checklist
More official notice for [this comment](https://github.com/lcm-proj/lcm/pull/310#issuecomment-1458418610).
=> Mark C# and Go and as Unmaintained

lcmgen/emit_lua.c
Changes the local `unpack` to fallback to `table.unpack`. This way Lua 5.4 still works, but Lua 5.1 can work as well.
=> Allow for old or new style Lua unpack

lcm/dbg.h, lcm/lcm_mpudpm.c, lcm/lcm_udpm.c
For the changes to debug, there is no need to malloc there because 256 chars is more than enough to hold everything in DBG_NAMETAB. But if there is garbage in that variable, make sure to null terminate.
For mpudpm and udpm, there is no need to copy past the end of the string, so use strcpy for that. There is no need for strncpy because the size is already checked in those functions.
=> Tweak previous strcpy changes

docs/release_checklist
The `.rockspec` file has a couple places where the version should be updated, so this PR tries to make that very clear. 
Also removes the instructions to manually create a zip archive. It appears that GitHub automatically creates a zip and tarball archive when a new release is associated with a tag, meaning that each release so far as had two identical zip archives. Removing the manually generated archive will be slightly less work and it will be less confusing for people trying to figure out which archive to download.
=> Update release checklist

.github/workflows/test.yml, lcm-lua/lualcm_lcm.c, lcm-lua/lualcm_pack.c, lcmgen/emit_lua.c, lcmgen/emit_python.c, lcmgen/tokenize.h
This PR:
- Adds two addition CI jobs which run the Ubuntu builds with release flags (ea8a7404496a1a0f9475f1b2efd70a1102a63314)
- Initializes variables with a nominal value (d9327cf9e8598761d04717c8954efbfdef2c79cc)
- Refactors size variables to an unsigned integer (b96cb3c9f4400a00d653cb0201c22c7cad276016)
- Decreases the size of C strings so they can be appended to without warnings occurring (745cdd2df465cff72ed6d56e082dfe9247d33273)
Resolves #457.
This PR does not fix [GCC 12 release build warnings](https://github.com/nosracd/lcm/actions/runs/5125792015/jobs/9219438195) (it is possible to use the Fedora target to produce those).
=> Fix Warnings in Release Build

lcm-lua/CMakeLists.txt
Unfortunately, it appears that if Werror is turned on in this fashion cmake won't let it be overridden via the usual command-line arguments:
- `-DCMAKE_C_FLAGS="-Wno-error" -DCMAKE_CXX_FLAGS="-Wno-error"`
- `--compile-no-warning-as-error`
This PR removes all arguments from `lcm-lua/CMakeLists.txt` which modify the number of warnings and how they're treated, instead preferring opt-in command-line arguments to increase the number of warnings and treat them as errors.
Resolves #457.
=> Optional Werror

.github/workflows/test.yml, format_code.sh
Different versions of `clang-format` format differently. The CI uses `clang-format-12` for consistency, but `format_code.sh` does not specify a version. This can result in situations where `format_code.sh` reports well-formatted code locally but not on the CI, such as [in this case](https://github.com/lcm-proj/lcm/pull/465#issuecomment-1638923774). 
b1c8fece231c77014e4def55a87650d98e53854a remedies this by forcing `format_code.sh` to use `clang-format-12` and instructing the user to install that particular version if it's not available.
Unfortunately, this means that some people are much older or newer distributions might not be able to use the formatter locally. While docker is always an option, 6932d24b2dca653cafd871f4dc82c4725baa4c8a attempts to ease this pain by printing the desired …
=> Better CI Format Check

lcm-python/lcm/__init__.py
pathlib was introduced in 3.4 (2014). Could also add the type hint `typing.Union[str, bytes, os.PathLike]`. PathLike is from py 3.6 (2016)
=> python: EventLog accept pathlib.Path

docs/content/build-instructions.md
The following command won't work on many systems, as `>` cannot be executed with root priviliges.
```sh
echo $LCM_LIBRARY_DIR > /etc/ld.so.conf.d/lcm.conf
```
Changed this command to:
```sh
echo $LCM_LIBRARY_DIR | sudo tee -a /etc/ld.so.conf.d/lcm.conf
```
Might not need the `-a` flag, since it seems unlikely that there's anything in that file that shouldn't be overwritten.
=> fix echo command in linux post-install instructions

lcmgen/emit_python.c
Python 2 support has been dropped so the `try ... execpt` of the py 2 module can be removed.
`import cStringIO.StringIO as BytesIO` was confusing pylance with `Module is not callable`. Therefore it couldn't determain that `encode` returned `bytes`.
=> lcmgen python: remove py 2 cStringIO compatibility

README.md, docs/index.rst
Resolves #471. There's not really a master list of minimum required versions anywhere so I've just documented the minimum required version of Python inside its bullet in the `Supported platforms and languages` lists.
=> Specify minimum required version of python

lcm/lcm_mpudpm.c, lcm/lcm_udpm.c, lcm/udpm_util.c, lcmgen/emit_go.c
I observed a warning like the following: 
```
==== LCM Warning ===                                                                                         
LCM detected that large packets are being received, but the kernel UDP                               
receive buffer is very small.  The possibility of dropping packets due to                             
insufficient buffer space is very high.                                                                                                              
For more information, visit:                                                                            
http://lcm-proj.github.io/multicast_setup.html  
```
When I followed the provided link I observed that the documentation page URL scheme had changed so I believe this points to the …
=> Update documentation links printed in warning output

lcm-logger/lcm_logger.c, lcm/lcm.c, lcmgen/emit_c.c, lcmgen/emit_python.c
The c code uses terse 2 letter names all the time. Makes reading it cumbersome. Should be worth doing a refactor pass.
Thoughts?
(Not talking about renaming any external symbol names. Just locals)
=> Attempt to improve names in C code

.gitignore, docs/content/contributing-c.md, docs/content/contributing-java.md, docs/content/contributing.md, docs/index.rst
Start basic documentation for project developers. Includes some notes discussed in #420.
I noticed that lcm-gen willfully leaks memory. That isn't really a problem for a short lived CLI tool, but I felt compelled that such reasoning should be documented somewhere.
Maintainers please add anything you feel is needed.
=> Basic contributing documentation

lcm-java/lcm/logging/LogPlayer.java, lcm-java/lcm/spy/Spy.java
Related to the works of #486:
Compilation was broken on latest Debian Sid (gcc-13) complaining about unmappable character (0xE2) for encoding US-ASCII. 
```bash
[ 24%] Building C object lcmgen/CMakeFiles/lcm-gen.dir/emit_cpp.c.o
cd /builds/jrivero-guest/lcm/debian/output/source_dir/obj-x86_64-linux-gnu/lcmgen && /usr/lib/ccache/cc  -I/builds/jrivero-guest/lcm/debian/output/source_dir/obj-x86_64-linux-gnu/lcmgen -I/builds/jrivero-guest/lcm/debian/output/source_dir/lcmgen -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -ffile-prefix-map=/builds/jrivero-guest/lcm/debian/output/source_dir=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu99 …
```
=> Use the 'bullet' utf-8 encoded value instead of the char directly

liblcm-test/lcm-example.1, liblcm-test/lcm-sink.1, liblcm-test/lcm-source.1, liblcm-test/lcm-tester.1
Related to the works of #486:
The QA checker in Debian was reporting that some of the man pages lacks of a brief description in the naming section. This is the full message: http://web.mit.edu/ebj/Desktop/ebj/MacData/afs/sipb/project/debathena/lintian/www/tags/manpage-has-bad-whatis-entry.html.
The changes in the PR deal with the missing descriptions. Please feel free to change/correct.
=> Include missing brief description in manpages

CMakeLists.txt, examples/c/CMakeLists.txt, examples/cpp/CMakeLists.txt, examples/cpp/lcm_log_writer/CMakeLists.txt, lcm-cmake/lcmUtilities.cmake
Recent versions of cmake produce the following warning for LCM:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
This PR fixes the warning by bumping the minimum required version of cmake from 3.1 to 3.5.
=> Bump Minimum Version of Cmake

lcmgen/emit_c.c
This PR fixes two warnings that occur when compiling the C output of lcm-gen. 
d70ca21a11cf950719eac356362a53a957652271 fixes an unused parameter warning resulting from #503.
c3a2daa683bd8d9ded60606b2028f9d59d425afa fixes a warning from passing a function pointer to `fprintf`, formatted using `%p`.
=> Fix lcm-gen output's compiler warnings

.github/workflows/test.yml, CMakeLists.txt, docs/content/build-instructions.md
The build instructions simply say `cmake ..` so I kinda assumed this was already in place.
=> Cmake: Set default build type to release

lcmgen/emit_go.c
Fixed -Wunused-result in lcmgen/emit_go.c without changing functionality
=> Fix -Wunused-result in lcmgen/emit_go.c without changing functionality

.github/workflows/test.yml, format_code.sh, lcm-logger/glib_util.c, lcm-python/module.c, lcm-python/pylcm.c, lcm/dbg.h
Ubuntu 24.04 does not have `clang-format-12` in its apt repository. Bump `clang-format-12` to `clang-format-15` as it is the latest version of clang-format available for Ubuntu 22.04.
=> Update clang format to version 15

cmake/FindGLib2.cmake
This PR implements the changes described and motivated in [this comment](https://github.com/lcm-proj/lcm/pull/442#issuecomment-2237343716).
=> Use pkgconfig to find glib

README.md, docs/content/install-instructions.md, docs/index.rst
Resolves #527.
You can preview these changes [on my fork](https://nosracd.github.io/lcm/index.html). Note that the new README link will be broken until the docs are deployed to this project's set of pages.
=> Documentation for installing LCM

lcm-logger/lcm_logger.c
Fix #464 
```
--disk-quota=SIZE      Minimum amount of free space the disk written to
must maintain. lcm-logger will exit if the quota is
exceeded. This is NOT an explicit limit on how much
lcm-logger is allowed to write.
Units accepted: B
1024: K,   M,   G,   T,   P,   E,
Ki,  Mi,  Gi,  Ti,  Pi,  Ei,
KiB, MiB, GiB, TiB, PiB, EiB
1000: KB, MB, GB, TB, PB, EB
e.g. "50G" or "0.05 TiB". 
Note: for `df`, -h is 1024 and -H is 1000 units.
Units are treated case insensitively. gb is treated
as GB (gigabytes) and not as gigabits.
NOT currently supported on Windows!
```
Currently put the check in the write thread and does not cause an immediate `exit(1)`. Please review.
=> lcm-logger: New `--disk-quota` flag

.github/workflows/build_wheels.yml, pyproject.toml, test/python/test_python_module.py
This PR adds a set of unit tests to test the Python module and wires the CI to run the tests for each wheel that gets built. Some platforms failed the test, mainly due to import errors (although one was unable to install the wheel), so these platforms no longer have wheels built for them:
- On macOS 13, for C Python versions 3.7 and 3.10 ([example import failure](https://github.com/nosracd/lcm/actions/runs/11635405758/job/32405760782#step:4:661), [example install failure](https://github.com/nosracd/lcm/actions/runs/11633905129/job/32400015118#step:4:622))
- All PyPy builds ([example import failure](https://github.com/nosracd/lcm/actions/runs/11636254406/job/32407305810#step:4:1017))
Also, it appears that the latest version of `cibuildwheel` now supports Python 3.13 so I bumped the …
=> Add Python tests

docs/content/python-notes.md, docs/index.rst, lcmgen/emit_python.c
Currently the `__init__.py` generated by lcm-gen exports symbols using the `from .file import Foo` pattern. Python has defined a set of conventions for exporting symbols:
https://typing.readthedocs.io/en/latest/spec/distributing.html#import-conventions
but the current approach does not follow any of the conventions defined by Python. While the current exports should generally still work it means that some tools won't be able to detect the symbols without implicitly exporting them. For example, running `mypy` with `--no-implicit-reexport` would cause errors like `error: Module "foo" does not explicitly export attribute "Foo"  [attr-defined]`.
This PR refactors the Python output to export symbols using one of the "redundant symbol alias" conventions defined by Python, or `from .file import …
=> Refactor exports to follow Python conventions

lcm-python/lcm/__init__.py
Resolves #550. 
Wraps the subprocess call in a `try`/`except` block, intercepting keyboard exceptions.
=> Catch Keyboard Exceptions

.github/workflows/test.yml, lcm-lua/CMakeLists.txt
Resolves #552. 
It appears on Windows lcm-lua needs to link against ws2_32. cff433f0e25e27070c29cbd5da2ae956bbd7a7d1 [reproduces the issue on CI](https://github.com/nosracd/lcm/actions/runs/12356152490/job/34481392150) and 5ff0302449286463f18d56b75517d3b963f4f18c addresses the issue.
=> Fix lua on windows

.github/workflows/test.yml, README.md, docker/Dockerfile.fedora, lcm/lcm_coretypes.h, lcm/windows/WinPorting.cpp
Currently the Windows and Fedora builds have compiler warnings when doing a release (default) build. This PR:
- Fixes the Fedora and Windows warnings for release builds
- Switches the Fedora build back to a release build
- Turns on Werror on the Windows builds
- Bumps Fedora to the latest release
=> Fix warnings

.github/workflows/build_wheels.yml, .github/workflows/test.yml, WinSpecific/README.md, test/python/test_python_module.py
Blocked by #547 (based off of its branch). This PR:
- Refactors the Windows jobs to no longer install or copy DLLs around before running the tests (I think this was made unnecessary by #521 refactoring the build targets to statically link)
- Refactors CI to no longer build with `-DPython_FIND_REGISTRY=NEVER` (doesn't seem to be necessary currently, although I kept the advice in `WinSpecific/README.md`). I'd be fine with keeping it around as a guard though.
- Refactors the Python module's tests to use `TemporaryDirectory` rather than `NamedTemporaryFile` (it was creating a file then overwriting it, which resulted in permissions errors on Windows)
- Adds a CI job to build a Windows wheel. This is something that has been requested (#526). Although I'm unsure how useful this particular wheel. …
=> Refactor windows stuff

NEWS.md, README.md, WinSpecific/README.md, docs/index.rst, docs/release_checklist
This PR:
- Specifies the minimum version of Python is 3.7
- Docs specified 3.6 but pyproject.toml requires 3.7
- 3.6 has been EOL for a few years now
- Updates the release checklist
- Removes section about mailing list, since it has been deactivated
- Adds section for creating a release on PyPi
- Adds a draft for release notes for 1.5.1 release
=> Update release docs

.github/workflows/build_wheels.yml, pyproject.toml
Follow-up to #557. `cibuildwheel` recently added support for an Ubuntu-based manylinux image for armv7, so this PR bumps the version of `cibuildwheel` to enable building manylinux wheels for armv7. Because the image is Ubuntu-based, this PR also overrides the `before-all` command for that image to install the necessary dependencies via apt.
=> Add support for manylinux armv7 wheels

.github/workflows/build_wheels.yml
Currently, the aarch64 wheel builds are failing due to a qemu bug:
- [failure on unrelated PR](https://github.com/lcm-proj/lcm/actions/runs/13217307278/job/36898086665)
- [failure on my fork](https://github.com/nosracd/lcm/actions/runs/13226754999/job/36918579212) (same revision as master here)
Relevant issue on cibuildwheel project discussing the bug: https://github.com/pypa/cibuildwheel/issues/2257
This PR bypasses the issue by switching to the native ARM GitHub runner. The advantages of this approach are:
Faster build times. For example, the Python 3.7 jobs that used qemu took:
- [ubuntu-latest | aarch64 | cp37-*](https://github.com/nosracd/lcm/actions/runs/12752220037/job/35541135201#logs): 13m 45s
- [ubuntu-latest | armv7l | …
=> Switch to using native arm runner

.github/workflows/deploy_docs.yml
Intended to fix [this failure](https://github.com/lcm-proj/lcm/actions/runs/13242356772) on master due to a too-old version of a github action.
=> Bump deploy pages actions versions

lcm-bazel/private/expand_flag_template.bzl, lcm-cmake/config.cmake, lcm-python/BUILD.bazel, lcm/BUILD.bazel, lcm/CMakeLists.txt, lcm/eventlog.h, lcm/lcm.h, lcm/lcm_c_namespace.h.in, lcm/meson.build, meson_options.txt
Add pre-processor option to change the C ABI symbol prefix. This allows multiple libraries to depend on independent copies of LCM.
There was already an LCM_NAMESPACE option for changing the names of the installed binaries, so the new option is LCM_C_NAMESPACE.
---
For the Bazel changes, we did a TRI review at https://github.com/jwnimmer-tri/lcm/pull/2, which is finished now.
=> Add LCM_C_NAMESPACE config option

CMakeLists.txt, examples/c/CMakeLists.txt, examples/cpp/CMakeLists.txt, examples/cpp/lcm_log_writer/CMakeLists.txt, lcm-cmake/lcmUtilities.cmake
macOS ships with cmake 4.0.1 which has dropped support for cmake < 3.5, leading to this error when building:
```
| Configuring the build directory with CMake version 4.0.1
| Running CMake with: -G Ninja -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=True -DLCM_ENABLE_EXAMPLES=False -DLCM_ENABLE_GO=False -DLCM_ENABLE_JAVA=False -DLCM_ENABLE_LUA=False -DLCM_ENABLE_PYTHON=False -DLCM_ENABLE_TESTS=False
|   - build directory:          /Users/silv/Documents/Research/Projects/navtk/build/subprojects/lcm/__CMake_build
|   - source directory:         /Users/silv/Documents/Research/Projects/navtk/subprojects/lcm
|   - toolchain file:           /Users/silv/Documents/Research/Projects/navtk/build/subprojects/lcm/__CMake_build/CMakeMesonToolchainFile.cmake
|   - preload file: …
```
=> upgrade minimum cmake version to 3.10

.github/workflows/build_wheels.yml, .github/workflows/test.yml
I saw some decent caching results on my fork from the `lukka/run-cmake` and `lukka/run-vcpk` actions but I'm disappointed by how unpredictable and often the cache misses are.
So this PR refactors to instead use the standard, but more manual `actions/cache` action. It sets `VCPKG_DEFAULT_BINARY_CACHE` to tell vcpkg to use a non-default directory for cache, adds a step to ensure that directory exists (in case there's a cache miss), and uses the action to save off and restore that directory.
The action is configured to save off two caches: one for `test.yml` and one for `build_wheels.yml`. They both need to cache win64 binaries but the latter also needs to cache win32 binaries. They are configured to get a cache miss if `vcpkg.json` changes, but start with a previous cache in the case of a …
=> Switch to manual cache action for vcpkg

.github/workflows/build_wheels.yml
Fixes an oversight in #567. Sets a couple cibuildwheel variables to enable cibuildwheel running the Python tests for each Windows wheel.
=> Enable tests on windows wheels

lcm-java/lcm-spy.sh.in
jchart2d can be installed to a system global directory while lcm-spy is installed to something like /usr/local.  Finding jchart2d in this case was not supported by the script.  We hardcode the typical path /usr/share/java since this is likely where it exists.
=> lcm-spy.sh: separate logic which finds jchart2d

docs/content/tutorial-cmake.md, lcm-cmake/lcmUtilities.cmake
This PR resolves #575.
To test, I developed this from following the tutorial:
[CMakeLists.txt](https://github.com/user-attachments/files/20746177/CMakeLists.txt)
Alongside it, I had `mytype.lcm` which contained:
```
package exlcm;
struct mytype
{
int64_t  timestamp;
double   position[3];
double   orientation[4];
int32_t  num_ranges;
int16_t  ranges[num_ranges];
string   name;
boolean  enabled;
}
```
16660db7c3dbfd1ae0fdf4eb124bd44dd2a09b40 may be enough to resolve the issue, but when trying to test it out I found that `FindPythonInterp` has been deprecated for a while so I updated the tutorial and `lcm_install_python` to use the replacement `FindPython`.
=> Fix Cmake Tutorial and Python Installation

docs/content/java-notes.md, lcm-java/CMakeLists.txt
Provide lcm-sources.jar to go along with lcm-jar. IDEs can use this as the source of documentation for the library. 
Idk if I'm cmaking correctly. This is a normal thing for java projects, but is not part of cmake's usejava.
=> Make lcm-sources.jar

examples/bazel/BUILD.bazel, lcm-bazel/lcm_cc_library_srcs.bzl, lcm-bazel/private/lcm_c_library_srcs.bzl, lcm-bazel/private/lcm_cc_library_srcs.bzl, lcm-bazel/private/lcm_java_library_srcs.bzl, lcm-bazel/private/lcm_py_library_srcs.bzl
This allows opt-in for C++11 mode (instead of C++98).
=> Add lcm-bazel option for passing args to lcmgen
