lcm-proj/lcm

lcm-java/lcm/spy/ObjectPanel.java

Checks to make sure we only add new points to the graph

---

lcm-java/lcm/spy/ObjectPanel.java
lcm-java/lcm/spy/ZoomableChartScrollWheel.java

Also increases FPS cap to 60fps from 20fps, producing much better looking charts on fast computers.

Fixes a bug in which the chart would jump when data was flowing in.

---

lcm-dotnet/lcm/lcm/UDPMulticastProvider.cs

corresponds to lcm-java version, resolving issue [#17](https://github.com/lcm-proj/lcm/issues/17)

Fixed lcm-dotnet Close() issue

---

lcmgen/emit_python.c

Fix for python code generation without package

---

docs/content/lua-api.md
docs/content/tutorial-lua.md
lcm-lua/lualcm_lcm.c
test/lua/client.lua

Based on #69, cherry picked the Lua related typos. Thanks @tbeu!

Fix Lua related typos

---

docs/content/tutorial-cmake.md
lcm-cmake/lcmUtilities.cmake
test/cpp/CMakeLists.txt
test/types/CMakeLists.txt

Add additional helper functions to deal with [a dependency issue](https://github.com/RobotLocomotion/drake/issues/3683) affecting some generators (at least Ninja). Rewrite CMake tutorial to reflect these changes, and also comments from #116 (which were punted partly to combine the rewrite with the updates for the new helpers in this branch).

CMake dependency improvements

---

lcm-logger/lcm_logger.c

Fix missing include

---

lcm-java/Makefile.am

Resolve #103 in the LTS version with autoconfigure

Resolve #103 for v1.3-lts - upgrade Java to -target 1.6

---

lcm-java/lcm/logging/Log.java

file to 2^31, getting closer to the 32 bit field set in the spec
Closes #144

Changes the upper bound check of the datalength field in the log

---

lcm-cmake/functions.cmake
lcm-java/jchart2d-code/CMakeLists.txt
lcm-java/lcm-logplayer-gui.sh
lcm-java/lcm-spy.sh

Also add third-party JAR dependencies when launching `lcm-spy`.

Java dependency fixes

---

lcm-lua/lualcm_pack.c

The Lua API for bytes was wrong up until now, and inconsistent with other
languages. It's fixed now, but the change will be incompatible with old code.
Please use Lua's `string.byte` if you still need the bytes as numbers!

Better handling of bytes in Lua

---

test/python/CMakeLists.txt

Fix PYTHON_SITE for tests

---

format_code.sh
lcm-python/module.c
lcm-python/pyeventlog.c
lcm-python/pylcm.c
lcm-python/pylcm.h
lcm-python/pylcm_subscription.c
lcm-python/pylcm_subscription.h

This one was pretty straightforward.

Formatting of LCM Python

---

format_code.sh
lcm-lua/.clang-format
lcm-lua/debug_support.h
lcm-lua/init.c
lcm-lua/lua_ref_helper.c
lcm-lua/lua_ref_helper.h
lcm-lua/lua_ver_helper.h
lcm-lua/lualcm_hash.c
lcm-lua/lualcm_hash.h
lcm-lua/lualcm_lcm.c
lcm-lua/lualcm_lcm.h
lcm-lua/lualcm_pack.c
lcm-lua/lualcm_pack.h
lcm-lua/test_unref.c
lcm-lua/utf8_check.c

Another straightforward reformat.

Formatting of LCM Lua

---

format_code.sh
liblcm-test/buftest-receiver.c
liblcm-test/buftest-sender.c
liblcm-test/lcm-example.c
liblcm-test/lcm-logfilter.c
liblcm-test/lcm-sink.c
liblcm-test/lcm-source.c
liblcm-test/lcm-tester.c

Formatting of liblcm-test

---

lcm-java/lcm-spy.sh.in

drop Xincgc flag for spy

---

lcmgen/emit_csharp.c

Fix issue #303 - forbidden implicit conversion double -> float

---

docs/content/lcm-type-ref.md

I always forget this nuance, and @jwnimmer-tri has reminded me on this a few times :facepalm: 
Here's my attempt to capture what I always miss.

docs: Expand on implementation for base hash vs. fingerprint

---

lcm-python/pyeventlog.c
lcm-python/pylcm.c
lcmgen/emit_python.c
test/python/bool_test.py
test/python/client.py

Resolves #358 
Resolves #347
We encounter this in Drake when using 20.04

Fix latent Python 3 test errors; fix PY_SSIZE_T_CLEAN DeprecationWarning

---

test/python/CMakeLists.txt
test/python/lcm_udpm_queue_issue_test.py

Test UDP Queue Overrun

---

.github/workflows/test.yml
docker/Dockerfile.fedora

This PR adds a CI test for Fedora via docker.

Fedora CI Target

---

docs/content/java-notes.md

Either a solution for #420 or just a stopgap until a more permanent solution can be found.

Remove outdated java build instructions

---

lcm-lua/CMakeLists.txt
lcm-lua/lualcm_hash.c
lcm-lua/lualcm_lcm.c
lcm-lua/lualcm_pack.c

Fixed a couple warnings. Some cleanup.

Fix warnings in Lua binding

---

lcmgen/emit_python.c

My second attempt at #470. The python tests pass though I'd like to see this tested with a larger project using lcm.

lcmgen python: import only the package when the package init is generated

---

lcmgen/emit_python.c

Fix regression in #491. Was broken in the case that the package was set to empty string.

lcmgen python: Fix imports when lcm package is left undefined

---

.github/workflows/test.yml
README.md
docker/Dockerfile.fedora

Update build targets to support Ubuntu 24.04 and Fedora 40.

Update workflows build targets

---

test/c/CMakeLists.txt
test/cpp/CMakeLists.txt

Puts a bandaid in place but does not resolve #523.

Disable failing tests
